name: Personal Website CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up environment variables
      run: |
        echo "DB_ENGINE=${{ secrets.DB_ENGINE }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
    - name: Install system dependencies
      run: |
        sudo apt-get -y install jq
        python -m pip install --upgrade pip
    - name: Install app dependencies
      run: |
        if [ -f Pipfile.lock ]; then
          jq -r '.default
               | to_entries[]
               | .key + .value.version' \
               Pipfile.lock > requirements.txt
          pip install -r requirements.txt
        fi
    - name: Run Tests
      run: |
        python manage.py test
